---
- Dev:
    - Tailscale Admin Console:
        - icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/tailscale.svg
          href: https://login.tailscale.com/admin
    - HomeLab VSCode:
        - icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/code.svg
          href: https://homelab.{{HOMEPAGE_VAR_TAILNET_NAME}}.ts.net/code
    - RPi VSCode:
        - icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/code.svg
          href: https://rpi.{{HOMEPAGE_VAR_TAILNET_NAME}}.ts.net/code
