---
- logo:
    icon: "{{HOMEPAGE_VAR_FAVICON}}"
- datetime:
    text_size: xs
    format:
      dateStyle: short
      timeStyle: long
- resources:
    cpu: true
    memory: true
    uptime: true
    disk: /
- resources:
    network: true
