---
# Homepage widgets (top bar)
- resources:
    cpu: true
    memory: true
- resources:
    cputemp: true
    uptime: true
- resources:
    expanded: true
    disk: /
- resources:
    expanded: true
    network: true
- datetime:
    text_size: xl
    format:
      dateStyle: short
      timeStyle: short
      hour12: true
