---
# Homepage widgets (top bar)
- logo:
    icon: "{{HOMEPAGE_VAR_FAVICON}}"
- datetime:
    text_size: 3xl
    format:
      dateStyle: short
      timeStyle: short
- resources:
    cpu: true
    memory: true
    uptime: true
    disk: /
