#!/usr/bin/env zsh

export PATH="$HOME/.local/bin:$PATH" # local binaries
export PATH="$HOME/go/bin:$PATH" # go binaries
export PATH="/snap/bin:$PATH" # snap store
export PIP_REQUIRE_VIRTUALENV=true # python

# history
export SHELL_SESSIONS_DISABLE=1
export HISTSIZE=5000
export SAVEHIST=$HISTSIZE
export HISTDUP=erase

# fix tmux + ssh issues
export TERM=xterm-256color

# Infrastructure
# =============================================================================

# mc env vars (generated by mc apply)
[[ -f "$HOME/.env" ]] && { set -a; source "$HOME/.env"; set +a; }

# machine config vars
[[ -n "$MC_HOME" && -n "$MC_ID" && -f "$MC_HOME/machines/$MC_ID/machine.env" ]] &&
{ set -a; source "$MC_HOME/machines/$MC_ID/machine.env"; set +a; }

# private secrets
[[ -n "$MC_PRIVATE" && -n "$MC_ID" && -f "$MC_PRIVATE/env/$MC_ID.env" ]] &&
{ set -a; source "$MC_PRIVATE/env/$MC_ID.env"; set +a; }

# machine-local overrides
[[ -f "$HOME/.zshenv.local" ]] && { set -a; source "$HOME/.zshenv.local"; set +a; }
