#!/usr/bin/env zsh

export PATH="$HOME/.local/bin:$PATH" # local binaries
export PATH="$HOME/go/bin:$PATH" # go binaries
export PATH="/snap/bin:$PATH" # snap store
export PIP_REQUIRE_VIRTUALENV=true # python

# history
export SHELL_SESSIONS_DISABLE=1
export HISTSIZE=5000
export SAVEHIST=$HISTSIZE
export HISTDUP=erase

# fix tmux + ssh issues
export TERM=xterm-256color

# Infrastructure
# =============================================================================

import_dotenv() {
    [[ -f "$1" ]] || return
    set -a; source "$1"; set +a
}

# mc env vars (generated by mc apply)
import_dotenv "$HOME/.env"

# machine config vars
[[ -n "$MC_HOME" && -n "$MC_ID" ]] &&
    import_dotenv "$MC_HOME/machines/$MC_ID/machine.env"

# private secrets
[[ -n "$MC_PRIVATE" && -n "$MC_ID" ]] && {
    import_dotenv "$MC_PRIVATE/env/$MC_ID.env"
    import_dotenv "$MC_PRIVATE/$MC_ID.env"
}

# machine-local overrides
import_dotenv "$HOME/.zshenv.local"
