#!/usr/bin/env zsh

export PATH="$HOME/.local/bin:$PATH" # local binaries
export PATH="$HOME/go/bin:$PATH" # go binaries
export PATH="/snap/bin:$PATH" # snap store
export PIP_REQUIRE_VIRTUALENV=true # python

# history
export SHELL_SESSIONS_DISABLE=1
export HISTSIZE=5000
export SAVEHIST=$HISTSIZE
export HISTDUP=erase

# fix tmux + ssh issues
export TERM=xterm-256color

# Infrastructure
# =============================================================================

dotenv::load() {
    [[ -f "$1" ]] || return
    set -a; source "$1"; set +a
}

# mc env vars (generated by mc apply)
dotenv::load "$HOME/.env"

# machine config vars
[[ -n "$MC_HOME" && -n "$MC_ID" ]] &&
    dotenv::load "$MC_HOME/machines/$MC_ID/machine.env"

# machine-local overrides
dotenv::load "$HOME/.zshenv.local"
