#!/usr/bin/env pwsh

# Environment
# =============================================================================

$env:PATH += "$([IO.Path]::PathSeparator)$HOME/.local/bin" # user local bin
$env:PIP_REQUIRE_VIRTUALENV = $true  # python

# Infrastructure
# =============================================================================

function Import-DotEnv($path)
{
    if (-not (Test-Path $path))
    { return
    }

    Get-Content $path | ForEach-Object {
        if ($_ -notmatch '^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$')
        { return
        }

        $val = $Matches[2] -replace '^["'']|["'']$', ''
        $val = [regex]::Replace($val, '\$\{?([A-Za-z_][A-Za-z0-9_]*)\}?', {
                param($m)
                $expanded = [System.Environment]::GetEnvironmentVariable($m.Groups[1].Value)
                if ($null -ne $expanded)
                { return $expanded
                }
                return $m.Value
            })
        [System.Environment]::SetEnvironmentVariable($Matches[1], $val)
    }
}

# mc env vars (generated by mc apply)
Import-DotEnv "$HOME/.env"

# machine config vars
if ($env:MC_HOME -and $env:MC_ID)
{
    Import-DotEnv "$env:MC_HOME/machines/$env:MC_ID/machine.env"
}

# private secrets
if ($env:MC_PRIVATE -and $env:MC_ID)
{
    Import-DotEnv "$env:MC_PRIVATE/env/$env:MC_ID.env"
    Import-DotEnv "$env:MC_PRIVATE/$env:MC_ID.env"
}

# Configuration
# =============================================================================

# homebrew
if (Test-Path -Path "/opt/homebrew/bin/brew")
{
    $(/opt/homebrew/bin/brew shellenv) | Invoke-Expression
} # arm macos
if (Test-Path -Path "/usr/local/bin/brew")
{
    $(/usr/local/bin/brew shellenv) | Invoke-Expression
} # intel macos
if (Test-Path -Path "/home/linuxbrew/.linuxbrew/bin/brew")
{
    $(/home/linuxbrew/.linuxbrew/bin/brew shellenv) | Invoke-Expression
} # linux/wsl

# oh-my-posh
oh-my-posh init pwsh --config "pure" | Invoke-Expression

# Completions
# =============================================================================

# tab-completion
Set-PSReadlineKeyHandler -Key Tab -Function MenuComplete

# homebrew completions
if (Get-Command brew -ErrorAction SilentlyContinue)
{
    if (Test-Path ($comp = "$env:HOMEBREW_PREFIX/share/pwsh/completions"))
    {
        foreach ($f in Get-ChildItem -Path $comp -File)
        {
            . $f
        }
    }
}

# uv completions (python version manager)
if (Get-Command uv -ErrorAction SilentlyContinue)
{
    (& uv generate-shell-completion powershell) | Out-String | Invoke-Expression
    (& uvx --generate-shell-completion powershell) | Out-String | Invoke-Expression
}

# dotnet completions
if (Get-Command dotnet -ErrorAction SilentlyContinue)
{
    dotnet completions script pwsh | Out-String | Invoke-Expression
}

# Infrastructure
# =============================================================================

# functions & aliases
. (Join-Path $PSScriptRoot "aliases.ps1")

# machine-specific extras
if (Test-Path (Join-Path $PSScriptRoot "profile.local.ps1"))
{
    . (Join-Path $PSScriptRoot "profile.local.ps1")
}
