#!/usr/bin/env zsh

# xdg base dirs
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_LOCAL_HOME="${XDG_LOCAL_HOME:-$HOME/.local}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$XDG_LOCAL_HOME/share}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-$XDG_LOCAL_HOME/state}"

# tools
export PIP_REQUIRE_VIRTUALENV=true # require virtual env for pip
export GOPATH="$XDG_LOCAL_HOME/go" # go workspace
export FPATH="$XDG_LOCAL_HOME/docker/completions:${FPATH}" # docker completions

# packages
export PATH="$XDG_LOCAL_HOME/bin:$PATH" # local binaries
export PATH="$GOPATH/bin:$PATH" # go binaries
export PATH="$PATH:/snap/bin" # snap store

# history
export SHELL_SESSIONS_DISABLE=1
export HISTSIZE=5000
export SAVEHIST=$HISTSIZE
export HISTDUP=erase

# zinit
export ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
export COMPLETIONS_PATH="$(dirname $ZINIT_HOME)/completions"
export FPATH="$COMPLETIONS_PATH:${FPATH}" # completions
