#!/usr/bin/env zsh

# Environment
# =============================================================================

# xdg base directories
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"

# local packages
export PATH="$HOME/.local/bin:$PATH"

# python
export PIP_REQUIRE_VIRTUALENV=true # require virtual env for pip

# go
export GOPATH="$HOME/.local/go"
export PATH="$GOPATH/bin:$PATH"

# snap store
export PATH="$PATH:/snap/bin"

# zinit
export ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
export COMPLETIONS_PATH="$(dirname $ZINIT_HOME)/completions"
export FPATH="$COMPLETIONS_PATH:${FPATH}" # completions

# shell history
export SHELL_SESSIONS_DISABLE=1
export HISTSIZE=5000
export SAVEHIST=$HISTSIZE
export HISTDUP=erase
