# Environment: Raspberry Pi
# =============================================================================

source "$MACHINE/config/core/zshenv" # global environment variables

# machine specific environment variables
export PATH="$PATH:/snap/bin"
