# Environment: Raspberry Pi
# =============================================================================

# set up machine environment
local script_dir=$(dirname "$(readlink -f "${BASH_SOURCE:-$0}")")
export MACHINE="$(dirname "$(dirname "$script_dir")")" # macos -> machines
source "$MACHINE/config/core/zshenv" # global environment variables

# machine specific environment variables
export PATH="$PATH:/snap/bin"
