"""Dotfile deployment: helpers and symlink logic."""

import logging
import os
from pathlib import Path

from machine.config import app_settings
from machine.manifest import Dotfile
from machine.platform import PLATFORM, Platform

logger = logging.getLogger(__name__)


# MARK: Dotfile Sets
#
# Each function returns dotfiles for a tool, resolving platform-specific
# target paths. Machines compose these in their manifests:
#
#   dotfiles = [*git(), *nvim(), *vscode(), ...]


def git() -> list[Dotfile]:
    """Git configuration."""
    dotfiles = [
        Dotfile(source="config/git/.gitconfig", target="~/.gitconfig"),
        Dotfile(source="config/git/.gitignore", target="~/.gitignore"),
    ]
    match PLATFORM:
        case Platform.WINDOWS:
            dotfiles.append(
                Dotfile(
                    source="config/git/.gitconfig.windows",
                    target="~/.gitconfig.platform",
                )
            )
        case Platform.WSL:
            dotfiles.append(
                Dotfile(
                    source="config/git/.gitconfig.wsl",
                    target="~/.gitconfig.platform",
                )
            )
    return dotfiles


def nvim() -> list[Dotfile]:
    """Neovim configuration."""
    match PLATFORM:
        case Platform.WINDOWS:
            target = "~/AppData/Local/nvim"
        case _:
            target = "~/.config/nvim"
    return [Dotfile(source="config/vim", target=target)]


def vscode() -> list[Dotfile]:
    """VS Code settings, keybindings, snippets, prompts, MCP."""
    match PLATFORM:
        case Platform.MACOS:
            base = "~/Library/Application Support/Code/User"
        case Platform.WINDOWS:
            base = "%APPDATA%/Code/User"
        case _:
            base = "~/.config/Code/User"
    return [
        Dotfile(source=f"config/vscode/{name}", target=f"{base}/{name}")
        for name in (
            "settings.json",
            "keybindings.json",
            "mcp.json",
            "snippets",
            "prompts",
        )
    ]


def ghostty() -> list[Dotfile]:
    """Ghostty terminal (macOS/Linux only)."""
    if PLATFORM == Platform.WINDOWS:
        return []
    return [
        Dotfile(
            source="config/ghostty.config",
            target="~/.config/ghostty/config",
        )
    ]


# MARK: Deployment


def deploy_dotfiles(dotfiles: list[Dotfile], root: Path) -> int:
    """Symlink all dotfiles. Returns count created/updated."""
    created = 0
    for df in dotfiles:
        src = root / df.source
        tgt = Path(os.path.expandvars(df.target)).expanduser()

        if not src.exists():
            logger.warning("Source not found: %s", src)
            continue
        if _symlink(src, tgt):
            created += 1
    return created


def write_env(machine_id: str, root: Path) -> None:
    """Write machine environment files (shell + PowerShell)."""
    env_dir = Path("~/.config/mc").expanduser()

    if app_settings.dry_run:
        logger.info("[dry-run] write env → %s", env_dir)
        return

    env_dir.mkdir(parents=True, exist_ok=True)

    # Shell (sh/zsh/bash)
    (env_dir / "env").write_text(
        "# Generated by mc setup - do not edit\n"
        f'export MC_HOME="{root}"\n'
        f'export MC_ID="{machine_id}"\n'
    )

    # PowerShell
    (env_dir / "env.ps1").write_text(
        "# Generated by mc setup - do not edit\n"
        f'$env:MC_HOME = "{root}"\n'
        f'$env:MC_ID = "{machine_id}"\n'
    )

    logger.info("Wrote env files: %s", env_dir)


# MARK: Symlink


def _symlink(source: Path, target: Path) -> bool:
    """Create or update a symlink. Returns True if changed."""
    if app_settings.dry_run:
        if target.is_symlink() and target.resolve() == source.resolve():
            return False
        logger.info("[dry-run] link %s → %s", target, source)
        return True

    target.parent.mkdir(parents=True, exist_ok=True)

    if target.is_symlink():
        if target.resolve() == source.resolve():
            logger.debug("OK: %s", target)
            return False
        logger.info("Update: %s → %s", target, source)
        target.unlink()
    elif target.exists():
        backup = target.with_suffix(target.suffix + ".backup")
        logger.info("Backup: %s → %s", target, backup)
        target.rename(backup)
    else:
        logger.info("Link: %s → %s", target, source)

    target.symlink_to(source)
    return True
