# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

multi-ecosystem-groups:
  monthly-dependencies:
    commit-message:
      prefix: "deps:"
    schedule:
      interval: "monthly"

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "monthly-dependencies"

  - package-ecosystem: "uv"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "monthly-dependencies"

  - package-ecosystem: "docker"
    directories: ["**/*"]
    patterns: ["*"]
    multi-ecosystem-group: "monthly-dependencies"

  - package-ecosystem: "docker-compose"
    directories: ["**/*"]
    patterns: ["*"]
    multi-ecosystem-group: "monthly-dependencies"
