#!/usr/bin/env pwsh
Import-Module PSReadLine
Import-Module PSFzf
Import-Module posh-git

# ═════════════════════════════════════════════════════════════════════════════
# MARK: Environment
# ═════════════════════════════════════════════════════════════════════════════

# User-installed binaries.
$env:PATH += "$([IO.Path]::PathSeparator)$HOME/.local/bin"
# Python - require virtualenv.
$env:PIP_REQUIRE_VIRTUALENV = $true
# Share MC_HOME with WSL.
$env:WSLENV = (@($env:WSLENV, 'MC_HOME/p') | Where-Object { $_ }) -join ':'

# ═════════════════════════════════════════════════════════════════════════════
# MARK: Infrastructure
# ═════════════════════════════════════════════════════════════════════════════

# Ensure HOME is available on Windows (used by .env expansions).
if ([string]::IsNullOrEmpty($env:HOME)) {
    $env:HOME = $env:USERPROFILE
}

function Import-DotEnv($path) {
    if (-not (Test-Path $path)) {
        return
    }

    Get-Content $path | ForEach-Object {
        if ($_ -notmatch '^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$') {
            return
        }

        $val = $Matches[2] -replace '^["'']|["'']$', ''
        $val = [regex]::Replace($val, '\$\{?([A-Za-z_][A-Za-z0-9_]*)\}?', {
                param($m)
                $expanded = [System.Environment]::GetEnvironmentVariable($m.Groups[1].Value)
                if ($null -ne $expanded) {
                    return $expanded
                }
                return $m.Value
            })
        [System.Environment]::SetEnvironmentVariable($Matches[1], $val)
    }
}

# Deployment variables (generated by mc).
Import-DotEnv "$HOME/.env"
# Machine variables.
Import-DotEnv "$env:MC_MACHINE/machine.env"

# ═════════════════════════════════════════════════════════════════════════════
# MARK: Homebrew
# ═════════════════════════════════════════════════════════════════════════════

# Homebrew bin paths.
$brewBins = @(
    '/opt/homebrew/bin/brew',
    '/usr/local/bin/brew',
    '/home/linuxbrew/.linuxbrew/bin/brew'
)

# Load Homebrew environment.
foreach ($brew in $brewBins) {
    if (-not (Test-Path $brew -PathType Leaf)) {
        continue
    }

    $brewEnv = & $brew shellenv pwsh
    if ($brewEnv) {
        $brewEnv | Out-String | Invoke-Expression
    }
    break
}

# Load Homebrew completions.
if (Test-Path ($comp = "$env:HOMEBREW_PREFIX/share/pwsh/completions")) {
    foreach ($f in Get-ChildItem -Path $comp -Filter '*.ps1' -File) {
        . $f
    }
}

Remove-Variable brewBins -ErrorAction SilentlyContinue
Remove-Variable brew -ErrorAction SilentlyContinue
Remove-Variable comp -ErrorAction SilentlyContinue
Remove-Variable f -ErrorAction SilentlyContinue

# ═════════════════════════════════════════════════════════════════════════════
# MARK: Configuration
# ═════════════════════════════════════════════════════════════════════════════

# Load user-defined completions.
$completionDirectory = Join-Path (Split-Path -Parent $PROFILE.CurrentUserAllHosts) 'completions'
Get-ChildItem -LiteralPath $completionDirectory -Filter '*.ps1' -File -ErrorAction SilentlyContinue |
    ForEach-Object { . $_.FullName }
Remove-Variable completionDirectory

# Tool completions.
if (Get-Command uv -ErrorAction SilentlyContinue) {
    uv generate-shell-completion powershell | Out-String | Invoke-Expression
}
if (Get-Command uvx -ErrorAction SilentlyContinue) {
    uvx --generate-shell-completion powershell | Out-String | Invoke-Expression
}
if (Get-Command dotnet -ErrorAction SilentlyContinue) {
    dotnet completions script pwsh | Out-String | Invoke-Expression
}

# Enable auto-suggestions.
Set-PSReadLineOption -PredictionSource History
# Enable fzf-based tab completion.
Set-PSReadLineKeyHandler -Key Tab -ScriptBlock { Invoke-FzfTabCompletion }
# Enable fzf tab expansion.
Set-PsFzfOption -TabExpansion

# Enable ctrl-r, ctrl-t, alt-c fzf bindings.
Set-PsFzfOption -PSReadlineChordProvider 'Ctrl+t'
Set-PsFzfOption -PSReadlineChordReverseHistory 'Ctrl+r'
Set-PsFzfOption -PSReadlineChordSetLocation 'Alt+c'
Set-PsFzfOption -TabCompletionPreviewWindow 'bottom|hidden'

# Enable starship theme.
Invoke-Expression (&starship init powershell)

# ═════════════════════════════════════════════════════════════════════════════
# MARK: Infrastructure
# ═════════════════════════════════════════════════════════════════════════════

# functions & aliases
. (Join-Path $PSScriptRoot "aliases.ps1")
# machine-specific extras
if (Test-Path (Join-Path $env:MC_MACHINE "profile.ps1")) {
    . (Join-Path $env:MC_MACHINE "profile.ps1")
}
