[tool.poetry]
name = "machine"
version = "0.1.6"
description = "Machine setup CLI app."
authors = ["Mohammed Fareed <mohdf.fareed@icloud.com>"]
readme = "README.md"
repository = "https://github.com/mohdfareed/machine"

packages = [
    { include = "app", from = "." },
]

include = [
    { path = "config" },
    { path = "scripts" }
]

[tool.poetry.scripts]
machine-setup = "app.main:app"

[tool.poetry.dependencies]
python = "^3.9.6" # default macos version
typer = "^0.15.1"
pydantic = "^2.10.4"
pydantic-settings = "^2.7.1"
platformdirs = "^4.3.6"

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.0.1"
pylint = "^3.3.3"
mypy = "^1.14.1"
pytest = "^8.3.4"
pytest-cov = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
strict = true

[tool.coverage.run]
omit = [
    "app/machines/*",
    "app/plugins/*",
    "app/pkg_managers/*"
]
