[tool.poetry]
name = "machine"
version = "0.1.1"
description = "Machine setup CLI app."
authors = ["Mohammed Fareed <mohdf.fareed@icloud.com>"]
readme = "README.md"
repository = "https://github.com/mohdfareed/machine"
packages = [
    { include = "app", from = "." },
    { include = "config", from = "." },
    { include = "scripts", from = "." }
]

[tool.poetry.scripts]
machine-setup = "app.main:app"

[tool.poetry.dependencies]
python = "^3.9.6" # default macos version
typer = "^0.12.4"
pydantic = "^2.9.2"
pydantic-settings = "^2.5.2"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.8.0"
pylint = "^3.3.0"
mypy = "^1.11.2"
pytest = "^8.3.3"
pytest-cov = "^5.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
reportConstantRedefinition = false
