[project]
name = "machine"
version = "0.2.0"
description = "Machine setup CLI app."
license = { text = "MIT" }
readme = "README.md"
authors = [
    {name = "Mohammed Fareed", email = "mohdf.fareed@icloud.com"}
]
urls = { repository = "https://github.com/mohdfareed/machine" }

# MARK: Dependencies

requires-python = ">=3.9.6" # default macos version

dependencies = [
    "typer",
    "rich",
    "pydantic",
    "pydantic-settings",
    "platformdirs",
]

[project.optional-dependencies]
dev = [
    "pre-commit", # pre-commit formatting hooks
    "pytest",     # testing
    "pytest-cov", # test coverage
    "pylance",    # language server
    "black",      # code formatting
    "isort",      # import formatting
]

# MARK: Poetry

[project.scripts]
machine-setup = "app.main:app"

[tool.poetry]
packages = [
    { include = "app", from = "." },
]
include = [
    { path = "config" }
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# MARK: Tools

[tool.pytest.ini_options]
testpaths = [
    "tests",
]

[tool.coverage.run]
omit = [
    "app/machines/*",
    "app/plugins/*",
]

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
