#!/usr/bin/env zsh

# =============================================================================
# MARK: Environment
# =============================================================================

export TERM=xterm-256color # fix tmux + ssh issues on ghostty
export SHELL_SESSIONS_DISABLE=1 # disable macOS per-session history
export PIP_REQUIRE_VIRTUALENV=true # python

typeset -U path
path=(
    "$HOME/.local/bin"
    "${GOPATH:-$HOME/go}/bin"
    /snap/bin
    $path
)
unset go_bin go_path

# =============================================================================
# MARK: Infrastructure
# =============================================================================

dotenv::load() {
    [[ -f "$1" ]] || return
    set -a; source "$1"; set +a
}

# deployment vars (generated by mc)
dotenv::load "$HOME/.env"
# machine vars
dotenv::load "$MC_MACHINE/machine.env"
