#!/usr/bin/env zsh

export TERM=xterm-256color # fix tmux + ssh issues
export SHELL_SESSIONS_DISABLE=1 # disable macOS per-session history
export PIP_REQUIRE_VIRTUALENV=true # python

# =============================================================================
# MARK: Infrastructure
# =============================================================================

dotenv::load() {
    [[ -f "$1" ]] || return
    set -a; source "$1"; set +a
}

# deployment vars (generated by mc)
dotenv::load "$HOME/.env"
# machine vars
dotenv::load "$MC_MACHINE/machine.env"

# Share command activation with mc without loading the interactive profile.
[[ -f "$MC_HOME/app/scripts/environment.unix.sh" ]] && source "$MC_HOME/app/scripts/environment.unix.sh"
