#!/usr/bin/env pwsh

# =============================================================================
# MARK: Environment
# =============================================================================

$env:PATH += "$([IO.Path]::PathSeparator)$HOME/.local/bin" # user local bin
$env:PIP_REQUIRE_VIRTUALENV = $true  # python

# Share MC_HOME with WSL
$env:WSLENV = (@($env:WSLENV, 'MC_HOME/p') | Where-Object { $_ }) -join ':'

# =============================================================================
# MARK: Infrastructure
# =============================================================================

function Import-DotEnv($path) {
    if (-not (Test-Path $path)) {
        return
    }

    Get-Content $path | ForEach-Object {
        if ($_ -notmatch '^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$') {
            return
        }

        $val = $Matches[2] -replace '^["'']|["'']$', ''
        $val = [regex]::Replace($val, '\$\{?([A-Za-z_][A-Za-z0-9_]*)\}?', {
                param($m)
                $expanded = [System.Environment]::GetEnvironmentVariable($m.Groups[1].Value)
                if ($null -ne $expanded) {
                    return $expanded
                }
                return $m.Value
            })
        [System.Environment]::SetEnvironmentVariable($Matches[1], $val)
    }
}

# Ensure HOME is available on Windows (used by .env expansions)
if ([string]::IsNullOrEmpty($env:HOME)) {
    $env:HOME = $env:USERPROFILE
}

# deployment vars (generated by mc)
Import-DotEnv "$HOME/.env"
# machine vars
Import-DotEnv "$env:MC_MACHINE/machine.env"

# =============================================================================
# MARK: Configuration
# =============================================================================

# homebrew
foreach ($brew in '/opt/homebrew/bin/brew', '/usr/local/bin/brew', '/home/linuxbrew/.linuxbrew/bin/brew') {
    if (-not (Test-Path $brew -PathType Leaf)) {
        continue
    }
    $brewEnv = & $brew shellenv pwsh
    if ($brewEnv) {
        $brewEnv | Out-String | Invoke-Expression
    }
    break
}

# homebrew completions
if (Test-Path ($comp = "$env:HOMEBREW_PREFIX/share/pwsh/completions")) {
    foreach ($f in Get-ChildItem -Path $comp -Filter '*.ps1' -File) {
        . $f
    }
}

# tools completions
if (Get-Command uv -ErrorAction SilentlyContinue) {
    uv generate-shell-completion powershell | Out-String | Invoke-Expression
}
if (Get-Command uvx -ErrorAction SilentlyContinue) {
    uvx --generate-shell-completion powershell | Out-String | Invoke-Expression
}
if (Get-Command dotnet -ErrorAction SilentlyContinue) {
    dotnet completions script pwsh | Out-String | Invoke-Expression
}

# oh-my-posh
oh-my-posh init pwsh --config "pure" | Invoke-Expression
# tab-completion
Set-PSReadlineKeyHandler -Key Tab -Function MenuComplete

# =============================================================================
# MARK: Infrastructure
# =============================================================================

# functions & aliases
. (Join-Path $PSScriptRoot "aliases.ps1")
# machine-specific extras
if (Test-Path (Join-Path $env:MC_MACHINE "profile.ps1")) {
    . (Join-Path $env:MC_MACHINE "profile.ps1")
}
