"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = """
$kubernetes\
$directory\
$git_branch\
$git_status\
$git_state\
$git_commit\
$all\
$shlvl\
$username\
$hostname\
$character
"""

# Prompt Line
# ═════════════════════════════════════════════════════════════════════════════

[username]
format = "[$user]($style)"
style_user = "red"
style_root = "bold bright-red"
# show_always = true

[hostname]
format = "[@](black)[$hostname]($style)[$ssh_symbol](bold $style) "
ssh_symbol = " "
style = "bright-green"
ssh_only = false

[shlvl]
disabled = false
style = "red"
symbol = "󰹍 "

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

# Header Line
# ═════════════════════════════════════════════════════════════════════════════

[directory]
style = "blue"
read_only = " 󰌾"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "bright-black"
symbol = " "

[git_commit]
only_detached = false
tag_disabled = false
tag_symbol = " "
format = "[$tag_symbol](purple)[$tag]($style) "
style = "bold bright-black"

[git_state]
style = "bright-black"
rebase = "rebasing"
merge = "merging"
revert = "reverting"
cherry_pick = "cherry-pickign"
bisect = "bisecting"
am = "AM"
am_or_rebase = "AM/rebase"

[git_status]
format = "\b[[(*$all_status)](218)( $ahead_behind(≡$stashed ))]($style)"
style = "bright-cyan"
# ahead = "↑"
# behind = "↓"
# diverged = "󰹹"
ahead = "⇡"
behind = "⇣"
diverged = "⬍"
conflicted = "\u200C"
stashed = "\u200C"
deleted = "\u200C"
renamed = "\u200C"
modified = "\u200C"
staged = "\u200C"
untracked = "\u200C"

[cmd_duration]
format = "[$duration]($style) "
style = "green"

# Icons
# ═════════════════════════════════════════════════════════════════════════════

# Nerd Font Symbols Preset: https://starship.rs/presets/nerd-font
# TODO: Check if up-to-date.
# Installer: `starship preset nerd-font-symbols -o ~/.config/starship.toml`

[aws]
symbol = " "

[azure]
symbol = " "

[battery]
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "
unknown_symbol = "󰂑 "
empty_symbol = "󰂎 "

[buf]
symbol = " "

[bun]
symbol = " "

[c]
symbol = " "

[cpp]
symbol = " "

[cmake]
symbol = " "

[cobol]
symbol = " "

[conda]
symbol = " "

[container]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[deno]
symbol = " "

[direnv]
symbol = " "

[docker_context]
symbol = " "

[dotnet]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[erlang]
symbol = " "

[fennel]
symbol = " "

[fortran]
symbol = " "

[fossil_branch]
symbol = " "

[gcloud]
symbol = "󱇶 "

[gleam]
symbol = " "

[golang]
symbol = " "

[gradle]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[helm]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[kubernetes]
symbol = "󱃾 "

[lua]
symbol = " "

[maven]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[mojo]
symbol = "󰈸 "

[nats]
symbol = " "

[netns]
symbol = "󰛳 "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[odin]
symbol = "󰟢 "

[opa]
symbol = " "

[openstack]
symbol = " "

[os.symbols]
AIX = " "
AlmaLinux = " "
Alpaquita = " "
Alpine = " "
ALTLinux = " "
Amazon = " "
Android = " "
AOSC = " "
Arch = " "
Artix = " "
Bluefin = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Elementary = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = " "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = " "
InstantOS = " "
Ios = "󰀷 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = " "
OpenCloudOS = " "
openEuler = " "
openSUSE = " "
OracleLinux = "󰺡 "
PikaOS = " "
Pop = " "
Raspbian = " "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "
Redox = "󰀘 "
RockyLinux = " "
Solus = " "
SUSE = " "
Ubuntu = " "
Ultramarine = " "
Unknown = " "
Uos = " "
Void = " "
Windows = "󰍲 "
Zorin = " "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[pixi]
symbol = "󰏗 "

[pulumi]
symbol = " "

[purescript]
symbol = " "

[python]
symbol = " "

[raku]
symbol = "󱖊 "

[red]
symbol = "󱍼 "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[singularity]
symbol = " "

[solidity]
symbol = " "

[spack]
symbol = " "

[status]
symbol = " "

[sudo]
symbol = " "

[swift]
symbol = " "

[terraform]
symbol = " "

[vlang]
symbol = " "

[typst]
symbol = " "

[vagrant]
symbol = " "

[xmake]
symbol = " "

[zig]
symbol = " "
