name: Set up environment
description: Set up the project's development environment

runs:
  using: "composite"
  steps:

    # set up and cache poetry
    - uses: actions/setup-python@main
      with:
        python-version: '3.9'
        cache: 'pip'
    - run: pip install poetry
      shell: sh

    # setup dev environment dependencies
    - run: | # ensure poetry uses cached pip packages
        poetry config virtualenvs.create false
        poetry install --with dev
      shell: sh

    # set author information
    - run: |
        git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
        git config --global user.name "${{ github.actor }}"
      shell: sh
