# Inputs
export MACHINE="{{ .machinePath }}"
export MACHINE_ID="{{ .machine }}"
export MACHINE_PRIVATE="{{ .privatePath }}"

# Convenience
export WSL="{{ .isWSL }}"
export MACHINE_SHARED="{{ .configPath }}"
export MACHINE_CONFIG="{{ .machineConfigPath }}"

# Load private -> shared -> machine config

if [[ -f "$MACHINE_PRIVATE/zshenv" ]]; then
    # shellcheck source=/dev/null
    source "$MACHINE_PRIVATE/zshenv"
fi

# shellcheck source=/dev/null
source "$MACHINE_SHARED/shell/zshenv"

if [[ -f "$MACHINE_CONFIG/zshenv" ]]; then
    # shellcheck source=/dev/null
    source "$MACHINE_CONFIG/zshenv"
fi
