# Configuration: Codespaces
# =============================================================================

# load core machine configuration
source $MACHINE/config/core/zshrc

# Functions and Aliases
# =============================================================================

alias setup-machine="machine-setup codespaces"
