#!/usr/bin/env zsh

# ═════════════════════════════════════════════════════════════════════════════
# MARK: Environment
# ═════════════════════════════════════════════════════════════════════════════

export SHELL_SESSIONS_DISABLE=1    # macOS - disable per-session history.
export PIP_REQUIRE_VIRTUALENV=true # Python - require virtualenv.

typeset -U path
path=(
  "$HOME/.local/bin"        # User-installed binaries.
  "${GOPATH:-$HOME/go}/bin" # Go binaries.
  "$HOME/.docker/bin"       # Docker binaries.
  /snap/bin                 # Snap binaries.
  $path
)

# ═════════════════════════════════════════════════════════════════════════════
# MARK: Infrastructure
# ═════════════════════════════════════════════════════════════════════════════

dotenv::load() {
  [[ -f "$1" ]] || return
  set -a; source "$1"; set +a
}

# Deployment variables (generated by mc).
dotenv::load "$HOME/.env"
# Machine variables.
dotenv::load "$MC_MACHINE/machine.env"
# Machine-specific extras.
[[ -f "$HOME/.zshenv.mc" ]] && source "$HOME/.zshenv.mc"
