#!/usr/bin/env zsh

# ═════════════════════════════════════════════════════════════════════════════
# MARK: Environment
# ═════════════════════════════════════════════════════════════════════════════

export SHELL_SESSIONS_DISABLE=1    # macOS - disable per-session history.
export PIP_REQUIRE_VIRTUALENV=true # Python - require virtualenv.

# WSL
if [ -f /proc/version ] && grep -qi microsoft /proc/version; then
  WSL=true
fi

# PATH
# ─────────────────────────────────────────────────────────────────────────────

typeset -U path
path=(
  "$HOME/.local/bin"        # User binaries.
  "$HOME/.docker/bin"       # Docker.
  "${GOPATH:-$HOME/go}/bin" # Go.
  /snap/bin                 # Snap.
  # 1Password.
  "/mnt/c/Users/$(whoami)/AppData/Local/Microsoft/WindowsApps"
  "/Applications/1Password.app/Contents/MacOS"
  $path
)

# ═════════════════════════════════════════════════════════════════════════════
# MARK: Infrastructure
# ═════════════════════════════════════════════════════════════════════════════

dotenv::load() {
  [[ -f "$1" ]] || return
  set -a; source "$1"; set +a
}

# Deployment variables (generated by mc).
dotenv::load "$HOME/.env"
# Machine variables.
dotenv::load "$MC_MACHINE/machine.env"
# Machine-specific extras.
[[ -f "$HOME/.zshenv.mc" ]] && source "$HOME/.zshenv.mc"
