"""Dotfiles manager.

Handles:
- Symlinking config files from config/ to home directory
- Machine-specific overrides from machines/{id}/
- Generating templated files (shell configs, gitconfig)
- Creating hushlogin
"""

from __future__ import annotations

from pathlib import Path
from typing import NamedTuple

from machine.core import (
    LINUX,
    MACOS,
    UNIX,
    WINDOWS,
    WSL,
    debug,
    get_machine_root,
    info,
    is_dry_run,
)


def _vscode_path(filename: str) -> str:
    """Get platform-specific VSCode config path."""
    if MACOS:
        return f"Library/Application Support/Code/User/{filename}"
    elif WINDOWS:
        return f"AppData/Roaming/Code/User/{filename}"
    else:  # Linux/WSL
        return f".config/Code/User/{filename}"


class DotfileLink(NamedTuple):
    """A dotfile symlink to create."""

    source: Path
    target: Path
    is_override: bool = False


def get_symlink_mappings() -> list[tuple[str, str]]:
    """Get dotfile mappings for direct symlinks.

    These are files that don't need templating.
    Format: (source_in_config, dest_in_home)
    """
    mappings = [
        # Vim/Neovim
        ("vim", ".config/nvim"),
        # VSCode
        ("vscode/settings.json", _vscode_path("settings.json")),
        ("vscode/keybindings.json", _vscode_path("keybindings.json")),
        ("vscode/snippets", _vscode_path("snippets")),
        ("vscode/prompts", _vscode_path("prompts")),
        # SSH config (not keys - those are handled by ssh.py)
        ("ssh.config", ".ssh/config"),
    ]

    # Platform-specific
    if UNIX:
        mappings.append(("ghostty.config", ".config/ghostty/config"))

    return mappings


def resolve_source(
    config_path: str, machine_id: str
) -> tuple[Path, bool] | None:
    """Resolve a config path, checking machine override first.

    Returns (source_path, is_override) or None if not found.
    """
    root = get_machine_root()
    machine_source = root / "machines" / machine_id / config_path
    base_source = root / "config" / config_path

    if machine_source.exists():
        return (machine_source, True)
    elif base_source.exists():
        return (base_source, False)
    return None


def create_symlink(link: DotfileLink) -> bool:
    """Create a symlink, handling existing files.

    Returns True if created/updated, False if unchanged.
    """
    source, target, is_override = link
    marker = " (override)" if is_override else ""

    # Ensure parent exists
    if not is_dry_run():
        target.parent.mkdir(parents=True, exist_ok=True)

    # Handle existing target
    if target.is_symlink():
        if target.resolve() == source.resolve():
            debug("dotfiles", f"already linked: {target}")
            return False
        info(f"updating link: {target}{marker}")
        if not is_dry_run():
            target.unlink()
    elif target.exists():
        backup = target.with_suffix(target.suffix + ".backup")
        info(f"backing up: {target} -> {backup}")
        if not is_dry_run():
            target.rename(backup)
    else:
        info(f"linking: {target}{marker}")

    if not is_dry_run():
        target.symlink_to(source)

    return True


def write_file(path: Path, content: str, description: str = "") -> bool:
    """Write a file, backing up if exists and different.

    Returns True if written, False if unchanged.
    """
    if path.exists():
        existing = path.read_text()
        if existing == content:
            debug("dotfiles", f"unchanged: {path}")
            return False
        backup = path.with_suffix(path.suffix + ".backup")
        info(f"backing up: {path} -> {backup}")
        if not is_dry_run():
            path.rename(backup)

    desc = f" ({description})" if description else ""
    info(f"writing: {path}{desc}")

    if not is_dry_run():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)

    return True


# =============================================================================
# Shell Config Generation
# =============================================================================


def generate_zshenv(machine_id: str, private_path: Path | None) -> str:
    """Generate .zshenv content with environment variables."""
    root = get_machine_root()
    private_str = str(private_path) if private_path else ""
    is_wsl = "true" if WSL else "false"

    return f'''# Generated by machine setup - do not edit directly
# Machine: {machine_id}

# Core paths
export MACHINE="{root}"
export MACHINE_ID="{machine_id}"
export MACHINE_PRIVATE="{private_str}"

# Convenience
export WSL="{is_wsl}"
export MACHINE_SHARED="{root}/config"
export MACHINE_CONFIG="{root}/machines/{machine_id}"

# Load: private -> shared -> machine
if [[ -f "$MACHINE_PRIVATE/zshenv" ]]; then
    source "$MACHINE_PRIVATE/zshenv"
fi

source "$MACHINE_SHARED/shell/zshenv"

if [[ -f "$MACHINE_CONFIG/zshenv" ]]; then
    source "$MACHINE_CONFIG/zshenv"
fi
'''


def generate_zshrc(machine_id: str) -> str:
    """Generate .zshrc content."""
    return f"""# Generated by machine setup - do not edit directly
# Machine: {machine_id}

# Load: shared -> machine
source "$MACHINE_SHARED/shell/zshrc"

if [[ -f "$MACHINE_CONFIG/zshrc" ]]; then
    source "$MACHINE_CONFIG/zshrc"
fi
"""


def generate_powershell_profile(
    machine_id: str, private_path: Path | None
) -> str:
    """Generate PowerShell profile content."""
    root = get_machine_root()
    private_str = str(private_path) if private_path else ""
    is_wsl = "true" if WSL else "false"

    return f'''# Generated by machine setup - do not edit directly
# Machine: {machine_id}

# Core paths
$env:MACHINE = "{root}"
$env:MACHINE_ID = "{machine_id}"
$env:MACHINE_PRIVATE = "{private_str}"

# Convenience
$env:WSL = "{is_wsl}"
$env:MACHINE_SHARED = "{root}/config"
$env:MACHINE_CONFIG = "{root}/machines/{machine_id}"

# Load: private -> shared -> machine
if (Test-Path "$env:MACHINE_PRIVATE/profile.ps1") {{
    . "$env:MACHINE_PRIVATE/profile.ps1"
}}

. "$env:MACHINE_SHARED/shell/profile.ps1"

if (Test-Path "$env:MACHINE_CONFIG/profile.ps1") {{
    . "$env:MACHINE_CONFIG/profile.ps1"
}}
'''


# =============================================================================
# Git Config Generation
# =============================================================================


def generate_gitconfig(machine_id: str) -> str:
    """Generate .gitconfig with include chain."""
    root = get_machine_root()

    lines = [
        "# Generated by machine setup - do not edit directly",
        f"# Machine: {machine_id}",
        "",
        "# Base configuration",
        "[include]",
        f"    path = {root}/config/git/.gitconfig",
    ]

    # Platform-specific includes
    if LINUX and not WSL:
        platform_file = root / "config" / "git" / ".gitconfig.linux"
        if platform_file.exists():
            lines += [
                "",
                "# Linux-specific",
                "[include]",
                f"    path = {platform_file}",
            ]
    elif MACOS:
        platform_file = root / "config" / "git" / ".gitconfig.macos"
        if platform_file.exists():
            lines += [
                "",
                "# macOS-specific",
                "[include]",
                f"    path = {platform_file}",
            ]
    elif WINDOWS and not WSL:
        platform_file = root / "config" / "git" / ".gitconfig.windows"
        if platform_file.exists():
            lines += [
                "",
                "# Windows-specific",
                "[include]",
                f"    path = {platform_file}",
            ]
    elif WSL:
        platform_file = root / "config" / "git" / ".gitconfig.wsl"
        if platform_file.exists():
            lines += [
                "",
                "# WSL-specific",
                "[include]",
                f"    path = {platform_file}",
            ]

    # Machine-specific include
    machine_gitconfig = root / "machines" / machine_id / ".gitconfig"
    if machine_gitconfig.exists():
        lines += [
            "",
            "# Machine-specific",
            "[include]",
            f"    path = {machine_gitconfig}",
        ]

    return "\n".join(lines) + "\n"


# =============================================================================
# Main Entry Points
# =============================================================================


def link_dotfiles(machine_id: str) -> int:
    """Link all dotfiles for a machine.

    Returns number of links created/updated.
    """
    info(f"linking dotfiles for: {machine_id}")
    created = 0

    for config_path, home_path in get_symlink_mappings():
        resolved = resolve_source(config_path, machine_id)
        if resolved is None:
            debug("dotfiles", f"not found: {config_path}")
            continue

        source, is_override = resolved
        target = Path.home() / home_path

        if create_symlink(DotfileLink(source, target, is_override)):
            created += 1

    # Link global gitignore
    root = get_machine_root()
    gitignore = root / "config" / "git" / ".gitignore"
    if gitignore.exists():
        if create_symlink(DotfileLink(gitignore, Path.home() / ".gitignore")):
            created += 1

    return created


def generate_shell_configs(machine_id: str, private_path: Path | None) -> int:
    """Generate shell configuration files.

    Returns number of files written.
    """
    info("generating shell configs...")
    written = 0
    home = Path.home()

    # Unix shell configs
    if UNIX:
        if write_file(
            home / ".zshenv", generate_zshenv(machine_id, private_path)
        ):
            written += 1
        if write_file(home / ".zshrc", generate_zshrc(machine_id)):
            written += 1

        # Create hushlogin
        hushlogin = home / ".hushlogin"
        if not hushlogin.exists():
            info("creating: .hushlogin")
            if not is_dry_run():
                hushlogin.touch()
            written += 1

    # PowerShell profile (all platforms can have pwsh)
    if WINDOWS:
        ps_profile = (
            home
            / "Documents"
            / "PowerShell"
            / "Microsoft.PowerShell_profile.ps1"
        )
    else:
        ps_profile = home / ".config" / "powershell" / "profile.ps1"

    if write_file(
        ps_profile, generate_powershell_profile(machine_id, private_path)
    ):
        written += 1

    return written


def generate_git_config(machine_id: str) -> bool:
    """Generate git configuration file.

    Returns True if written, False if unchanged.
    """
    info("generating git config...")
    return write_file(
        Path.home() / ".gitconfig",
        generate_gitconfig(machine_id),
        "with includes",
    )


def setup_dotfiles(machine_id: str, private_path: Path | None = None) -> None:
    """Full dotfiles setup: generate configs + create symlinks."""
    # Generate templated configs
    generate_git_config(machine_id)
    generate_shell_configs(machine_id, private_path)

    # Symlink static configs
    created = link_dotfiles(machine_id)
    info(f"dotfiles setup complete ({created} links)")
