# Homepage - Homelab Dashboard

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "*"
      HOMEPAGE_VAR_TITLE: ${HOMEPAGE_TITLE:-Homepage}
      HOMEPAGE_VAR_FAVICON: ${HOMEPAGE_FAVICON:-mdi-home-analytics}
      HOMEPAGE_VAR_TAILNET_NAME: ${TAILNET_NAME}
      HOMEPAGE_VAR_TAILSCALE_API_KEY: ${TAILSCALE_API_KEY}
      HOMEPAGE_VAR_TAILSCALE_HOMELAB_DEVICE_ID: ${TAILSCALE_HOMELAB_DEVICE_ID}
      HOMEPAGE_VAR_TAILSCALE_RPI_DEVICE_ID: ${TAILSCALE_RPI_DEVICE_ID}
      HOMEPAGE_VAR_TAILSCALE_PC_DEVICE_ID: ${TAILSCALE_PC_DEVICE_ID}
