---
# Service widgets shown on the dashboard.

- Services:
- Infrastructure:
    - Tailscale:
        icon: tailscale
        href: https://login.tailscale.com/admin
        description: VPN mesh network
        widget:
          type: tailscale
          deviceid: "{{HOMEPAGE_VAR_TAILSCALE_DEVICE_ID}}"
          key: "{{HOMEPAGE_VAR_TAILSCALE_KEY}}"
          fields: ["address", "last_seen", "expires"]
    - Watchtower:
        icon: watchtower
        description: Automatic container updates
        server: docker
        container: watchtower
        widget:
          type: watchtower
          url: http://host.docker.internal:8080
          key: "{{HOMEPAGE_VAR_WATCHTOWER_KEY}}"
          fields:
            ["containers_scanned", "containers_updated", "containers_failed"]
