name: Continuous Deployment

on:
  push:
    branches: [main]
  workflow_dispatch:

  workflow_call:
    outputs:
      run_id:
        value: ${{ github.run_id }}

permissions:
  contents: write
  pull-requests: write

jobs:
  dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Set up environment
        uses: ./.github/setup

      - name: Update dependencies
        run: ./scripts/update.sh

      - name: Create pull request
        uses: peter-evans/create-pull-request@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'Update dependencies'
          branch: 'deps'
          sign-commits: true
          labels: 'CD'
