name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:

permissions:
  contents: read

jobs:
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-python: true
      - uses: actions/cache@v5
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('uv.lock') }}

      # Sync, format, lint, and type check
      - run: uv sync --dev --locked
      - name: Check formatting
        run: uv run ruff format --check src/ tests/
      - name: Run linter
        run: uv run ruff check src/ tests/
      - name: Run type checker
        run: uv run pyright src/ tests/

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -e SC1071

  spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: reviewdog/action-misspell@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: warning
          locale: "US"
          exclude: |
            *.lock
