name: Deploy Release

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Create a new release'
        default: true
        type: boolean
      increment:
        description: 'Version increment type'
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

permissions:
  contents: write
  pull-requests: write

jobs:
  versioning:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.resolver.outputs.version }}
      tag: v${{ steps.resolver.outputs.version }}

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Set up environment
        uses: ./.github/setup

      - name: Get current version
        id: previous-version
        run: |
          version=$(poetry version | cut -d' ' -f2)
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Update version
        id: semver
        uses: WyriHaximus/github-action-next-semvers@master
        with:
          version: ${{ steps.previous-version.outputs.version }}

      - name: Resolve new version
        id: resolver
        run: |
          case ${{ github.event.inputs.increment }} in
            major)
            version=${{ steps.semver.outputs.major }} ;;
            minor)
            version=${{ steps.semver.outputs.minor }} ;;
            patch)
            version=${{ steps.semver.outputs.patch }} ;;
            esac
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Update project version
        id: update_version
        env:
          version: ${{ steps.resolver.outputs.version }}
        run: poetry version ${{ env.version }}

      - name: Update repository
        env:
          tag: v${{ steps.resolver.outputs.version }}
        run: |
          git add pyproject.toml
          git commit --no-verify -m "release: update project to ${{ env.tag }}" || exit 0
          git push
          echo "::notice::Updated project to ${{ env.tag }}"

  tag:
    runs-on: ubuntu-latest
    needs: [versioning]

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Create tag
        env:
          tag: ${{ needs.versioning.outputs.tag }}
        run: |
          git pull
          git tag ${{ env.tag }}

      - name: Push tag
        env:
          tag: ${{ needs.versioning.outputs.tag }}
        run: git push origin ${{ env.tag }} --force
